### ISSUE TITLE
Cannot register a new user using GUI

### ISSUE THREAD

**Issue by rojagit** [aws-samples/aws-serverless-appsync-loyalty#2]
No errors, it goes to Confirm Code, even Re-send code sends nothing to email.
Has this app been tested ? I can provide a public URL if someone wants to check it out.

**Comment by KoldBrewEd** [comment]
Sure, it has been tested live on twitch and it's now available on YouTube: https://www.youtube.com/watch?v=WOQIqRVzkas

Suggest to sign up a user with both e-mail and a valid phone number (with country code). You should receive the code via SMS as per the video above.

**Comment by rojagit** [comment]
Why do you close this even before giving me a chance to check again ? 

I have tested many other starter amplify apps here, and while most are very flaky, one or two actually worked well with cognito. SO, I know what I am doing when I register a new user. I have tried nearly 10 times to register a user in your app. Unlike other apps, which dont even bother giving an error, I think yours did, and it was error free but no emails sent. 

Your Youtube video skips the registration piece. WHY ? Can you post one showing registration ? Of course you can blacken the email out.

And to top it  all AWS sent me some billing alert saying I am using 85% of my DynamoDB capacity when all I did were check out these starter apps and hardly did anything with them. I deleted my free AWS account before they can charge me for some nonsense. Scary.

**Comment by KoldBrewEd** [comment]
It's closed because it cannot be replicated. This app just uses the higher order component from Amplify. Suggest to open an issue in the amplify repo.

**Comment by rojagit** [comment]
Gotcha...thanks!
