### ISSUE TITLE
Why use AWS Mobile?

### ISSUE THREAD

**Issue by dancomanlive** [aws-samples/aws-serverless-appsync-loyalty#6]
AWS Amplify is the next generation of AWS Mobile so why still use AWS Mobile?

**Comment by KoldBrewEd** [comment]
It does use AWS Amplify, just not the AWS Amplify CLI. When this was created the AWS Amplify CLI didn't exist and the AWS Mobile CLI was the tool of choice.

Eventually I'll work on porting it to the AWS Amplify CLI, when time allows, in the mean time pull requests are always very welcome.
