### ISSUE TITLE
how to identify no of active subscribers by subscription

### ISSUE THREAD

**Issue by ghost** [aws-samples/aws-serverless-appsync-loyalty#7]
Need to keep count of how many subscribers are connected with each subscription. 

For UserA, UserB are connected with SubscriptionA : then 2 is the total subscribers
For UserA are connected with SubscriptionB : then 1 is the total subscribers

Can i know when UserA unsubscribes , subscribes, disconnects, reconnects from AppSync ?

**Comment by KoldBrewEd** [comment]
You have to implement presence detection logic yourself, this is not supported out of the box by AppSync
